services:
  db:
    container_name: db_django_auth
    image: postgres:16
    environment:
      POSTGRES_DB: "postgresdb"
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: "Asia/Tokyo"
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  backend:
    container_name: backend_django_auth
    build: 
      context: .
      dockerfile: app/backend/Dockerfile
    env_file: ./.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy